// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzcotxppypgqobawppoh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Y290eHBweXBncW9iYXdwcG9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMTUzODEsImV4cCI6MjA2Mjg5MTM4MX0.5YTVZ1T1IOYXCKSeueDEP50Gk-cqbWlhUNpcbVKWlkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);